import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, ChefHat, HelpCircle, MessageCircleMore, ShieldCheck, ShoppingBag } from "lucide-react";
import { PageHero, SectionIntro } from "@/components/ui";
import { SubmissionForm } from "@/components/submission-form";
import { TrackedAnchor } from "@/components/tracked-anchor";
import { siteCopy } from "@/content";
import { whatsappHref } from "@/lib/site";

export const metadata: Metadata = siteCopy.pages.contact.metadata;

export default function ContactPage() {
  const whatsapp = whatsappHref("Hello Omala, I would like help with…");
  return (
    <>
      <PageHero {...siteCopy.pages.contact.hero} actions={<><Link className="button button--accent" href="#contact-form">Send a message <ArrowRight size={17} /></Link>{whatsapp ? <TrackedAnchor className="button button--ghost-light" href={whatsapp} target="_blank" rel="noreferrer" eventName="whatsapp_click" eventContext="contact_hero">Open WhatsApp</TrackedAnchor> : null}</>} aside={<ul className="aside-list"><li><ShoppingBag size={18} /> Include an Omala receipt ID if the message concerns an order.</li><li><ChefHat size={18} /> Kitchen decision-makers can apply directly on the For Kitchens page.</li><li><ShieldCheck size={18} /> Never send payment credentials, ID documents or customer lists.</li></ul>} />

      <section className="content-section content-section--cream"><div className="shell"><SectionIntro eyebrow="The quickest path" title="Start with the form made for your request." align="center" /><div className="contact-methods"><article className="contact-method"><span className="icon-tile"><ShoppingBag size={22} /></span><h3>Food order</h3><p>Ask for today’s menu or start an individual order request.</p><Link className="card-link" href="/order" style={{ marginTop: 18 }}>Start an order <ArrowRight size={15} /></Link></article><article className="contact-method"><span className="icon-tile icon-tile--warm"><ChefHat size={22} /></span><h3>Kitchen pilot</h3><p>Tell us how the kitchen operates and apply for the one-month pilot.</p><Link className="card-link" href="/for-kitchens#apply" style={{ marginTop: 18 }}>Apply now <ArrowRight size={15} /></Link></article><article className="contact-method"><span className="icon-tile"><HelpCircle size={22} /></span><h3>Something else</h3><p>Use the general form below for support, partnership and privacy questions.</p><a className="card-link" href="#contact-form" style={{ marginTop: 18 }}>Send a message <ArrowRight size={15} /></a></article></div></div></section>

      <section className="form-section" id="contact-form"><div className="shell form-layout"><aside className="form-aside"><span className="eyebrow">General message</span><h2>Give us enough context to route it well.</h2><p>Do not use this form for urgent food-safety emergencies or to send sensitive documents.</p><div className="form-assurance"><span><MessageCircleMore size={16} /> We will reply through the phone, WhatsApp or email details you provide.</span><span><ShieldCheck size={16} /> Marketing permission is optional and does not affect our reply.</span></div></aside><SubmissionForm endpoint="/api/forms/contact" formName="contact" successPath="/confirmation/contact" submitLabel="Send message" eventContext="contact"><fieldset className="form-group"><legend>Your details</legend><div className="field-grid"><label className="field"><span>Name <em>*</em></span><input name="name" autoComplete="name" required /></label><label className="field"><span>WhatsApp or phone <em>*</em></span><input name="phone" inputMode="tel" autoComplete="tel" required /></label><label className="field--full"><span>Email</span><input name="email" type="email" autoComplete="email" /></label></div></fieldset><fieldset className="form-group"><legend>Your message</legend><div className="field-grid"><label className="field--full"><span>Topic <em>*</em></span><select name="topic" defaultValue="" required><option value="" disabled>Choose a topic</option><option>Order support</option><option>Kitchen application</option><option>Group order</option><option>Partnership</option><option>Privacy or data request</option><option>Marketing preferences</option><option>Other</option></select></label><label className="field--full"><span>Message <em>*</em></span><textarea name="message" minLength={10} placeholder="Add any receipt ID and the practical details we need to understand the request." required /></label></div></fieldset><div className="consent-block"><h3>Reply permission and optional news</h3><label className="check-row check-row--required"><input type="checkbox" name="serviceContactConsent" value="true" required /><span>Omala may contact me to reply to this message. *</span></label><label className="check-row"><input type="checkbox" name="consentMarketingWhatsApp" value="true" /><span>Also send me optional Omala updates by WhatsApp.</span></label><p>Read our <Link href="/privacy">privacy notice</Link>.</p></div></SubmissionForm></div></section>
    </>
  );
}
